### ISSUE TITLE
Should `exists` API only return true for `active` identities?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-identity#15]
In looking at instances where we might make use of the new `exists` API, I see that some cases are only interested in identities where ```sysStatus === 'active'```

Should exists only return `true` for active (non-deleted) identities?

If so, I notice that we do not have an index on the sysStatus field, should we have such an index?

One use case is here:
https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/index.js#L328-L332

**Comment by dlongley** [comment]
> If so, I notice that we do not have an index on the sysStatus field, should we have such an index?

Don't need an index for that unless we're not providing the ID.

Good question about `sysStatus === 'active'` ... it should probably be an option (add `options` param to `exists`). And we'll need to figure out what the default should be.

**Comment by dlongley** [comment]
There's an option to pass `status` now in the upcoming 5.x version. Closing.
