### ISSUE TITLE
generateResource docs, name, alternative

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock-identity#17]
Current `generateResource()` docs should note that it is returning a transformed copy of the role argument and removing the `generateResource` property.  It also has a strange name.  Maybe it should be `generateRoleResource` or something?

However, perhaps that function should just go away.  Are there just two users of this functionality at the moment in bedrock-identity and bedrock-consumer?  It looks like they both are doing somewhat the same thing: preparing a freshly copied identity by doing in-place update of roles if the `generateResource` property is `id`.  The bedrock-identity version also throws an error if it doesn't know how to handle that properties value.

Maybe there should be a new bedrock-identity callback based API function to do this?  `api.setupRoles(identity, callback)` (or some other name).  It would do the role processing loop, `generateResource === 'id'` check, and error checking in one place.  Based on the two current use cases it could be an in-place process on a passed identity.  Or callback could return a new identity if that makes more sense.

Thoughts?

**Comment by mattcollier** [comment]
The documentation does say it returns a transformed role?  Do you want to change the wording? https://github.com/digitalbazaar/bedrock-identity/blob/master/lib/index.js#L72-L79

Seeing as we just got this in, and as you point out, it's only used in two places, I don't feel a burning need to iterate any further at this time.

**Comment by davidlehn** [comment]
It should at least say it's returning a transformed copy of the role.  It's unclear if it's doing in-place transformation or not which users of the function need to know.

**Comment by mattcollier** [comment]
Would an in-place transformation be documented with an `@return`?  It was my assumption that `@return` indicates the return value of the function.

**Comment by davidlehn** [comment]
Either way.  Main doc is fine.  Just should be clear what it's doing.  Something like: "Copies a role and inserts the specified ID into the new role's resource restriction array."

**Comment by dlongley** [comment]
Closing to archive repo.
