### ISSUE TITLE
We should switch to schema.org:Organization and schema.org:memberOf

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-identity#22]
@davidlehn said:
>Why was https://www.w3.org/ns/activitystreams#Group chosen for Group? It's the only activitystreams property here. Is the intent to also add this to the main w3id.org/identity context too?
> 
> As a datapoint, I didn't realize "ActivityStreams" defined Groups and similar until just now. It might confused others too.
> 
> It looks like https://schema.org/memberOf is used to specify Groups. The schema.org spec says memberOf values are expected to be schema:Organization or schema:ProgramMembership.
> 
> Will the usage of Group and memberOf here cause possible confusion with other tools and people? 'm not sure what other schemas might better cover this. Classic semantic web problem. FOAF has Agent, Group, Person, Organization, member, etc, but I'm not sure what a similar "memberOf" property is. Perhaps https://www.w3.org/TR/vocab-org/ is of use. It uses FOAF though the terminology is more like orgs and sub orgs than "groups".

We decided to not use schema.org Organization initially as we thought it was too restrictive. We used Activity Streams because the semantic meaning was closest to what we wanted and we use AS for a bunch of LDN stuff. The W3C published vocabulary is probably the correct one to use, but its not used widely.

Perhaps schema.org Organization and schema.org memberOf is the one we want to use given all the benefits and small downside. That said, I've opened an issue, but merging this PR.

**Comment by davidlehn** [comment]
Also worth considering: https://www.w3.org/wiki/WebAccessControl
They use WebIDs for groups, not sure what type they are, and foaf:member for membership.

**Comment by dlongley** [comment]
Closing to archive repo.
