### ISSUE TITLE
Add capability cache feature to reduce database load on permission checks

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-identity#23]
We currently have a delegateCapability feature where modules may implement an event listener to add additional resources to a permission check. This allows modules to grant actors the ability to take actions with resources that they don't have explicit capabilities for. This event is emitted during a permission check and works fine for simple resource translations but not complex ones that require lots of database hits. We should add a complementary feature that fires when a call is made to update a capability cache. 

We need an API that lets you write to the capability cache and we need a built-in event (on the permission check) that will read from that cache and automatically populate the resource list.

**Comment by dlongley** [comment]
To be clear, that "built-in event (on the permission check)" that reads from the cache should be implemented with a built-in `bedrock-identity.delegateCapability.translate` event handler.

**Comment by dlongley** [comment]
The capability cache should have one document per identity to reduce potential race conditions.

**Comment by dlongley** [comment]
Closing to archive repo.
